### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: 1372

### ISSUE THREAD

**Issue by heqian1024** [hellobike/tunnel#6]
**正常运行一段时间后报错，异常信息如下：**

java.lang.ArrayIndexOutOfBoundsException: 1372
	at com.hellobike.base.tunnel.parse.EventParser$Lexer.current(EventParser.java:178) ~[tunnel-server-1.0.0-SNAPSHOT.jar:?]
	at com.hellobike.base.tunnel.parse.EventParser.parseValue(EventParser.java:129) ~[tunnel-server-1.0.0-SNAPSHOT.jar:?]
	at com.hellobike.base.tunnel.parse.EventParser.parseEvent(EventParser.java:100) ~[tunnel-server-1.0.0-SNAPSHOT.jar:?]
	at com.hellobike.base.tunnel.parse.EventParser.parse(EventParser.java:62) ~[tunnel-server-1.0.0-SNAPSHOT.jar:?]
	at com.hellobike.base.tunnel.TunnelServer.receiveStream(TunnelServer.java:173) ~[tunnel-server-1.0.0-SNAPSHOT.jar:?]
	at com.hellobike.base.tunnel.TunnelServer.access$900(TunnelServer.java:43) ~[tunnel-server-1.0.0-SNAPSHOT.jar:?]
	at com.hellobike.base.tunnel.TunnelServer$ReceiveTask.run(TunnelServer.java:236) ~[tunnel-server-1.0.0-SNAPSHOT.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202-ea]
[2019-06-14 15:13:32.471] [ INFO] [ReceiveThread-tunnel] [c.h.b.t.TunnelServer                    ] GetRplConnection success,slot:tunnel
[2019-06-14 15:13:32.473] [ INFO] [ReceiveThread-tunnel] [c.h.b.t.TunnelServer                    ] GetRplStream success,slot:tunnel
[2019-06-14 15:13:32.473] [ INFO] [ReceiveThread-tunnel] [c.h.b.t.TunnelServer                    ] recover logical replication success,slot:tunnel,cost:12ms
[2019-06-14 15:13:34.481] [ WARN] [ReceiveThread-tunnel] [c.h.b.t.TunnelServer                    ] receive msg failure,try to recover.
java.lang.ArrayIndexOutOfBoundsException: null

**Comment by xiaoma20082008** [comment]
@heqian1024 你的表结构是什么样子的？插入的sql是什么？

**Comment by heqian1024** [comment]
**表结构**
CREATE TABLE db40t.t_mon_kafka
(
update_cnt numeric(20,0),
update_time timestamp without time zone
)

**sql**
update db40t.t_mon_kafka set update_time = now() ,update_cnt = update_cnt + 1;

**表原来没有主键，昨天我建了主键，加了个主键字段，运行1天了，到现在为止没有异常，不知道是不是因为没有主键的问题**

**Comment by heqian1024** [comment]
**我改了一下源代码，把报错时的消息(message)打印出来了，跟我配置的同步的表没有关系，是其他未配置的表导致的。只要我更新一下表里面的这条数据就会报错，信息如下：**
```
[2019-06-17 12:15:20.647] [ INFO] [ReceiveThread-tunnel] [c.h.b.t.p.EventParser                   ] 
message:table db40.stk850: UPDATE: seq[numeric]:840318 ctime[timestamp without time zone]:'2019-06-17 10:08:40.525474' mtime[timestamp without time zone]:'2019-06-17 10:08:40.525474' rtime[timestamp without time zone]:'2019-06-17 12:15:21.16615' isvalid[numeric]:1 remark[text]:null proid_stk850[character varying]:'P000911894' f001v_stk850[character varying]:'丧尸未逝' f002v_stk850[character varying]:'681001' f003v_stk850[character varying]:'电影' f004v_stk850[character varying]:'喜剧;恐怖' f005n_stk850[numeric]:1 f006d_stk850[date]:'2019-06-14' f007n_stk850[numeric]:1 f008v_stk850[character varying]:'20190617,etool_10084044854.png' f009v_stk850[character varying]:'吉姆·贾木许' f010v_stk850[character varying]:'科洛·塞维尼;亚当·德赖弗;蒂尔达·斯文顿;史蒂夫·布西密;奥斯汀·巴特勒;比尔·默瑞;卡赖伯·兰德里·琼斯;赛琳娜·戈麦斯;卡罗尔·凯恩;汤姆·威兹;罗茜·佩雷兹;丹尼·格洛弗;罗伯特·菲茨杰拉德·迪格斯;伊基·波普;罗莎尔·卡农;萨拉·戴维' f011v_stk850[character varying]:null f012v_stk850[character varying]:null datasource[character varying]:'CLR' modifysource[character varying]:'CLR' f013v_stk850[character varying]:'美国' f014t_stk850[text]:'电影故事发生在寂静的小镇森特维尔，有些事情不太对劲。月亮又大又低地挂在天空中，白天的时间变得不可预测，动物开始表现出不寻常的行为。没人知道原因。新闻报道是可怕的，科学家们对此感到担忧。但没有人预见到，人们很快就会迎来最奇怪、最危险的后果：死人不会死——他们从坟墓里爬出来，野蛮地攻击活人，并大肆享用——镇上的居民必须为生存而战。' f015v_stk850[character varying]:'The Dead Don''t Die'
[2019-06-17 12:15:20.647] [ WARN] [ReceiveThread-tunnel] [c.h.b.t.TunnelServer                    ] receive msg failure,try to recover.
java.lang.ArrayIndexOutOfBoundsException: 1246
	at com.hellobike.base.tunnel.parse.EventParser$Lexer.current(EventParser.java:190) ~[tunnel-server-1.0.0-SNAPSHOT.jar:?]
	at com.hellobike.base.tunnel.parse.EventParser.parseValue(EventParser.java:141) ~[tunnel-server-1.0.0-SNAPSHOT.jar:?]
	at com.hellobike.base.tunnel.parse.EventParser.parseEvent(EventParser.java:112) ~[tunnel-server-1.0.0-SNAPSHOT.jar:?]
	at com.hellobike.base.tunnel.parse.EventParser.parse(EventParser.java:70) ~[tunnel-server-1.0.0-SNAPSHOT.jar:?]
	at com.hellobike.base.tunnel.TunnelServer.receiveStream(TunnelServer.java:173) ~[tunnel-server-1.0.0-SNAPSHOT.jar:?]
	at com.hellobike.base.tunnel.TunnelServer.access$900(TunnelServer.java:43) ~[tunnel-server-1.0.0-SNAPSHOT.jar:?]
	at com.hellobike.base.tunnel.TunnelServer$ReceiveTask.run(TunnelServer.java:236) ~[tunnel-server-1.0.0-SNAPSHOT.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202-ea]
```

**Comment by heqian1024** [comment]
**您好，字段中有2个引号就会报错，tunnel连接上之后，我在数据库中建了以下这张表，插入一条数据，见下方sql，就报错了。**
create table test0617(info text);
insert into test0617 values($$asdf''sa$$);

**Comment by xiaoma20082008** [comment]
> **您好，字段中有2个引号就会报错，tunnel连接上之后，我在数据库中建了以下这张表，插入一条数据，见下方sql，就报错了。**
> create table test0617(info text);
> insert into test0617 values($$asdf''sa$$);

好的，我先瞅瞅，3Q
